### ISSUE TITLE
Models -> plugin.js

### ISSUE THREAD

**Issue by DanielWGross** [DanielWGross/cardinalRecording#47]
# DISCUSSION:
Need to determine if this table is necessary. There is no relationship between the plug-ins and any other table.  Could this just be put into the equipment table?

See equipment.js issue for more info...

**Comment by mccaffertycr** [comment]
Plugins have a hasmany relationship with equipment, we could add the plugins as additional Boolean columns in the equipment model but I think it helps to separate them being that there are almost as many plugins are there are entries in the equipment table.

**Comment by DanielWGross** [comment]
Does it need to have a relationship with equipment? There is no shared information between the two that is really necessary. The only value I see in separating them would be if there were plugins that matched up with microphones, cables, amps, etc but I don't believe that is the case.

**Comment by mccaffertycr** [comment]
Although we aren’t using the foreign key, the relationship is convienent
with sequelize because we can use the include object to add them as an
array when we equipment.findall and not have to findall({}) on multiple
tables. That being said it probably makes sense to just incorporate it into
equipment directly, I’ll do a pass after I get the plugin seeds together
where I put everything in the equipment model.

**Comment by DanielWGross** [comment]
We can discuss more in person on Saturday. I'm not for or against either method just not sure what makes the most sense. I think initially we were lacking on DB tables and thought it would look better to spread out the data. At this point, we have quite a few tables and likely more coming once we implement the login information and it is probably wise to condense where possible.
